# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
version: 2
updates:
  # Gradle build files (build.gradle, build.gradle.kts)
  - package-ecosystem: "gradle"
    directory: "/"                   # Location of build files
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10     # Optional: Limit PRs

  # Version catalog (libs.versions.toml)
  - package-ecosystem: "gradle"
    directory: "/gradle"             # If your TOML is in /gradle, update this path
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10     # Optional: Limit PRs

   Optionally, include submodules if you have them
   - package-ecosystem: "gradle"
    directory: "/submodule"
    schedule:
      interval: "daily"
